# Generated by Django 5.0.4 on 2024-07-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="rubrics",
        ),
        migrations.RemoveField(
            model_name="rubric",
            name="submission",
        ),
        migrations.AlterField(
            model_name="rubric",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubrics",
                to="regai.assignment",
            ),
        ),
    ]
