# Generated by Django 5.0.4 on 2024-07-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="rubric",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
