# Generated by Django 5.0.4 on 2024-07-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regai", "0002_remove_assignment_rubrics_remove_rubric_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rubric",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="regai.submission",
            ),
        ),
        migrations.AlterField(
            model_name="rubric",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="regai.assignment",
            ),
        ),
    ]
