# Generated by Django 5.0.4 on 2024-07-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regai", "0002_alter_assignment_rubric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentagent",
            name="configuration",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
