# Generated by Django 5.0.4 on 2024-07-12 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regai", "0003_rubric_submission_alter_rubric_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rubric",
            name="submission",
        ),
        migrations.AlterField(
            model_name="rubric",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubrics",
                to="regai.assignment",
            ),
        ),
    ]
