# Generated by Django 5.0.4 on 2024-07-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regai", "0004_alter_agentaction_output_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="category_scores",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="grading_critique",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="overall_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
