# Generated by Django 5.0.4 on 2024-08-14 14:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regai", "0004_remove_rubric_submission_alter_rubric_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="critique",
            name="revision_status",
            field=models.CharField(
                choices=[
                    ("PASS", "Pass"),
                    ("MINOR_REVISION", "Minor Revision"),
                    ("MAJOR_REVISION", "Major Revision"),
                ],
                default="PASS",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SCORMData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cmi_core_lesson_status",
                    models.CharField(default="not attempted", max_length=50),
                ),
                ("cmi_core_score_raw", models.FloatField(blank=True, null=True)),
                ("cmi_core_score_min", models.FloatField(default=0.0)),
                ("cmi_core_score_max", models.FloatField(default=100.0)),
                (
                    "cmi_core_total_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("cmi_suspend_data", models.TextField(blank=True)),
                ("cmi_interactions", models.JSONField(default=list)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorm_data",
                        to="regai.assignment",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorm_data",
                        to="regai.submission",
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "submission")},
            },
        ),
    ]
